name       : direnv
version    : 2.15.2
release    : 3
source     :
    - https://github.com/direnv/direnv/archive/v2.15.2.tar.gz : 35076978e2ccbd367043e8aa33ba4268c03270a68bac3789262dacb3b26115c2
license    : MIT
component  : programming.tools
summary    : direnv is an environment switcher for the shell.
description: |
    direnv is an environment switcher for the shell. It knows how to hook into bash, zsh, tcsh and fish shell to load or unload environment variables depending on the current directory. This allows project-specific environment variables without cluttering the "~/.profile" file.
builddeps  :
    - golang
install    : |
    cd ..
    mkdir src
    mv direnv-$version src/direnv
    export GOPATH=`pwd`
    cd src/direnv
    %make_install DESTDIR=$installdir/usr
