name       : direnv
version    : 2.17.0
release    : 4
source     :
    - https://github.com/direnv/direnv/archive/v2.17.0.tar.gz : 1402cfbd9988cfe86d0ded47bd9732a061581f04bdb6275f156d8654e4d09a3a
license    : MIT
component  : programming.tools
summary    : direnv is an environment switcher for the shell.
description: |
    direnv is an environment switcher for the shell. It knows how to hook into bash, zsh, tcsh and fish shell to load or unload environment variables depending on the current directory. This allows project-specific environment variables without cluttering the "~/.profile" file.
builddeps  :
    - golang
install    : |
    cd ..
    mkdir src
    mv direnv-$version src/direnv
    export GOPATH=`pwd`
    cd src/direnv
    %make_install DESTDIR=$installdir/usr
