name       : direnv
version    : 2.13.3
release    : 2
source     :
    - https://github.com/direnv/direnv/archive/v2.13.3.tar.gz : 2d5569ef08a919e02d8b229b8f71ca01a0f3920e7e14f0b10c0df76bb4ea57a1
license    : MIT
component  : programming.tools
summary    : direnv is an environment switcher for the shell.
description: |
    direnv is an environment switcher for the shell. It knows how to hook into bash, zsh, tcsh and fish shell to load or unload environment variables depending on the current directory. This allows project-specific environment variables without cluttering the "~/.profile" file.
builddeps  :
    - golang
install    : |
    cd ..
    mkdir src
    mv direnv-$version src/direnv
    export GOPATH=`pwd`
    cd src/direnv
    %make_install DESTDIR=$installdir/usr
